# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SetUp NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 16.3.0

      - uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose up --exit-code-from automation

      - run: npm install
      - run: npm run test:regression
      - name: Install Allure CommandLine
        run: npm i -g allure-commandline
      - name: Generate Allure Reports
        run: npm run generate-report
      - run: ls -lrt
