# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: SetUp NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: 18.3.0

      - name: actions/checkout@v2
      - run: npm install
      # run utility services in the background
      # using docker-compose (see docker-compose.yml file)

      - uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose up -d

      - name: Tests
        continue-on-error: false
        run: npm run test:regression

      - name: Generate Report
        if: always()
        run: npm run allure-report-generate
      - name: Publishing Allure artifact to Github Actions
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: allure-report
          path: allure-report/
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      - name: Test marketplace action
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 10
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
